version: '3'
services:
  api-gateway:
    build: ./services/api_gateway
    ports:
      - "8000:8000"
  auth-svc:
    build: ./services/auth_svc
    ports:
      - "8001:8001"
  ai-gateway:
    build: ./services/ai_gateway
    ports:
      - "8002:8000"
  automation-svc:
    build: ./services/automation_svc
    ports:
      - "8003:8000"
  pg-db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
