name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: pre-commit/action@v3.0.1
      - name: Install dependencies
        run: |
          pip install -r requirements.txt || true
      - name: Run tests
        run: |
          pytest -q || true
